### ISSUE TITLE
衛星計畫材料

### ISSUE THREAD

**Issue by ChenPoWei** [cypherpunks-core/Satellite-project#1]
參考：https://github.com/cypherpunks-core/Satellite-project/blob/master/article/building-your-own-bitcoin-satellite-node-part1.md

- [x] 筆電-一台裝有Linux筆電 ，最好有i5 ，硬碟要求 裝的下220GB全節點(最低要求3G修剪過的節點): https://amzn.to/2x6G86r
- [x] 至少46公分（18英寸）衛星天線: https://amzn.to/2wBtPzK
- [x] 軟體定義的無線電接口(Software Defined Radio Interface): https://amzn.to/2g8Nu2O
- [x] Linear Polarization (線性極化) PLL LNB: https://amzn.to/2w0Zk4C
- [x] LNB 安裝支架: https://amzn.to/2xgotXU
- [x] LNB 電源: https://amzn.to/2KUGouq
- [x] 同軸電纜: https://amzn.to/2w7N4xQ
- [x] F連接器到SMA同軸適配器（F Connector to SMA Coax Adapter）: https://amzn.to/2gajpAh
- [x] 用於調整配件的螺絲起子和鉗子
- [x] (選則)3英尺，衛星三腳架: https://amzn.to/2w81RZm

**Comment by ChenPoWei** [comment]
**_所以 總共需要42.99+25.95+1.75+6.68=USD77.37(台幣2321.1)
再加上Linear Polarization (線性極化) PLL LNB ，應該貴不到哪去？_**

* USD42.99  至少46公分（18英寸）衛星天線: https://amzn.to/2wBtPzK
* USD25.95 軟體定義的無線電接口(Software Defined Radio Interface): https://amzn.to/2g8Nu2O
* USD 1.75 LNB 安裝支架: https://amzn.to/2xgotXU
* USD 6.68 LNB 電源: https://amzn.to/2KUGouq

感覺實驗室有：
* USD14.00 同軸電纜: https://amzn.to/2w7N4xQ
* USD 7.60 F連接器到SMA同軸適配器（F Connector to SMA Coax Adapter）: https://amzn.to/2gajpAh

感覺非必要：
* USD35.75 (選則)3英尺，衛星三腳架: https://amzn.to/2w81RZm

找不報價 Linear Polarization (線性極化) PLL LNB: https://amzn.to/2w0Zk4C

**Comment by awesome-doge** [comment]
已經順利 取得組裝所有材料
